language: cpp

git:
  depth: 10

notifications:
  email: false

addons:
  apt:
    packages:
      - libssl-dev
      - python-dev
      - scons
      - swig

sudo: required

matrix:
  include:
    - os: linux
      compiler: gcc
      dist: trusty
    - os: osx
      compiler: clang
      env: OPENSSL1.1=false
    - os: osx
      compiler: clang
      env: OPENSSL1.1=true

before_install:
- |
  if [[ "${TRAVIS_OS_NAME}" == "osx" && OPENSSL1.1 == "false" ]]; then
    brew update
    brew install swig
    brew outdated openssl || brew upgrade openssl
    brew outdated cmake || brew upgrade cmake
  fi
- |
  if [[ "${TRAVIS_OS_NAME}" == "osx" && OPENSSL1.1 == "true" ]]; then
    brew update
    brew install swig
    brew outdated openssl || brew upgrade openssl
    brew outdated cmake || brew upgrade cmake
  fi
- python -V

script:
- ./travis.sh


